[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#F63366"      
backgroundColor = "#0F172A"   
secondaryBackgroundColor = "#1E293B"  
textColor = "#F8FAFC"
font = "sans serif"
