[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#F63366"
backgroundColor = "#000000"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#f0f0f5"
font = "sans serif"
